import { Routes } from '@angular/router';

import { UsuarioComponent } from './usuario/usuario.component';
import { ElasticidaComponent } from './elasticida/elasticida.component';
import { NutricionaleComponent } from './nutricionale/nutricionale.component';
import { AntropometricaComponent } from './antropometrica/antropometrica.component';
import { EntrenadorComponent } from './entrenador/entrenador.component';
import { PsicologoComponent } from './psicologo/psicologo.component';
import { MedicoComponent } from './medico/medico.component';
import { AsistenciaComponent } from './asistencia/asistencia.component';
import { PagoComponent } from './pago/pago.component';
import { RepresentanteComponent } from './representante/representante.component';
import { RepresentantenadadorComponent } from './representantenadador/representantenadador.component';
import { TorneoComponent } from './torneo/torneo.component';
import { CategoriadistanciaComponent } from './categoriadistancia/categoriadistancia.component';
import { TiemponadadorComponent } from './tiemponadador/tiemponadador.component';
import { GrupoComponent } from './grupo/grupo.component';
import { CiudadComponent } from './ciudad/ciudad.component';
import { GeneroComponent } from './genero/genero.component';
import { AreanadoComponent } from './areanado/areanado.component';
import { CategoriapruebaComponent } from './categoriaprueba/categoriaprueba.component';
import { CategoriatipoComponent } from './categoriatipo/categoriatipo.component';
import { TiponadoComponent } from './tiponado/tiponado.component';
import { TipopagoComponent } from './tipopago/tipopago.component';
import { PruebatorneoComponent } from './pruebatorneo/pruebatorneo.component';
import { PruebanadadorComponent } from './pruebanadador/pruebanadador.component';
import { PlanPagoComponent } from './plan-pago/plan-pago.component';
import { AbonopagoComponent } from './abonopago/abonopago.component';
import { GraficasComponent } from './graficas/graficas.component';
import { GraficasUsuarioComponent } from './graficas-usuario/graficas-usuario.component';
import { AsistenciaUsuarioComponent } from './asistencia-usuario/asistencia-usuario.component';

export default [
    { path: 'usuario', component: UsuarioComponent},
    { path: 'entrenador', component: EntrenadorComponent },
    { path: 'elasticida', component: ElasticidaComponent },
    { path: 'nutricionales', component: NutricionaleComponent },
    { path: 'antropometrica', component: AntropometricaComponent },
    { path: 'psicologo', component: PsicologoComponent },
    { path: 'medico', component: MedicoComponent },
    { path: 'asistencia', component: AsistenciaComponent },
    { path: 'pago', component: PagoComponent },
    { path: 'representante', component: RepresentanteComponent },
    { path: 'representantenadador', component: RepresentantenadadorComponent },
    { path: 'torneo', component: TorneoComponent },
    { path: 'categoriaDistancia', component: CategoriadistanciaComponent },
    { path: 'tiempoNadador', component: TiemponadadorComponent },
    { path: 'grupo', component: GrupoComponent },
    { path: 'ciudad', component: CiudadComponent },
    { path: 'genero', component: GeneroComponent },
    { path: 'areaNado', component: AreanadoComponent },
    { path: 'categoriaProducto', component: CategoriapruebaComponent },
    { path: 'categoriaTipo', component: CategoriatipoComponent },
    { path: 'tipoNado', component: TiponadoComponent },
    { path: 'tipoPago', component: TipopagoComponent },
    { path: 'pruebaTorneo', component: PruebatorneoComponent },
    { path: 'pruebaNadador', component: PruebanadadorComponent },
    { path: 'planPago', component: PlanPagoComponent },
    { path: 'abonoPago', component: AbonopagoComponent },
    { path: 'graficas', component: GraficasComponent },
    { path: 'graficasUsuario', component: GraficasUsuarioComponent },
    { path: 'asistenciaUsuario', component: AsistenciaUsuarioComponent },
    { path: '**', redirectTo: '/notfound' }
] as Routes;
