import { Routes } from '@angular/router';

import { UsuarioComponent } from './usuario/usuario.component';
import { ElasticidaComponent } from './elasticida/elasticida.component';
import { NutricionaleComponent } from './nutricionale/nutricionale.component';
import { AntropometricaComponent } from './antropometrica/antropometrica.component';
import { EntrenadorComponent } from './entrenador/entrenador.component';
import { PsicologoComponent } from './psicologo/psicologo.component';
import { MedicoComponent } from './medico/medico.component';
import { AsistenciaComponent } from './asistencia/asistencia.component';
import { PagoComponent } from './pago/pago.component';
import { RepresentanteComponent } from './representante/representante.component';
import { RepresentantenadadorComponent } from './representantenadador/representantenadador.component';
import { TorneoComponent } from './torneo/torneo.component';
import { CategoriadistanciaComponent } from './categoriadistancia/categoriadistancia.component';
import { TiemponadadorComponent } from './tiemponadador/tiemponadador.component';
import { GrupoComponent } from './grupo/grupo.component';
import { CiudadComponent } from './ciudad/ciudad.component';
import { GeneroComponent } from './genero/genero.component';
import { AreanadoComponent } from './areanado/areanado.component';
import { CategoriapruebaComponent } from './categoriaprueba/categoriaprueba.component';
import { CategoriatipoComponent } from './categoriatipo/categoriatipo.component';
import { TiponadoComponent } from './tiponado/tiponado.component';
import { TipopagoComponent } from './tipopago/tipopago.component';
import { PruebatorneoComponent } from './pruebatorneo/pruebatorneo.component';
import { PruebanadadorComponent } from './pruebanadador/pruebanadador.component';
import { PlanPagoComponent } from './plan-pago/plan-pago.component';
import { AbonopagoComponent } from './abonopago/abonopago.component';
import { GraficasComponent } from './verGraficas/graficas.component';
import { GraficasUsuarioComponent } from './graficas-usuario/graficas-usuario.component';
import { AsistenciaUsuarioComponent } from './asistencia-usuario/asistencia-usuario.component';
import { MedidasUsuarioComponent } from './medidas-usuario/medidas-usuario.component';
import { ReportesComponent } from './reportes/reportes.component';
import { ComprovanteComponent } from './comprovante/comprovante.component';
import { PagoEntrenadoresComponent } from './pago-entrenadores/pago-entrenadores.component';
import { RegistroMedicoComponent } from './registro-medico/registro-medico.component';
import { RegistroPsicologoComponent } from './registro-psicologo/registro-psicologo.component';
import { HistorialUsuarioComponent } from './historial-usuario/historial-usuario.component';
import { VermedidasComponent } from './verMedidas/vermedidas.component';
import { MedicoUsuarioComponent } from './verMedicoUsuario/medico-usuario.component';
import { VerpagoComponent } from './verPago/verpago.component';
import { VertorneocompetidaComponent } from './verTorneoCompetida/vertorneocompetida.component';
import { VerdashboarComponent } from './verDashboarUsuario/verdashboar.component';
import { AbonoentrenadorComponent } from './abonoentrenador/abonoentrenador.component';
import { EntrenadorgrupoComponent } from './entrenadorgrupo/entrenadorgrupo.component';
import { VerentrenadorusuarioComponent } from './verentrenadorusuario/verentrenadorusuario.component';
import { ReporteentrenadoresComponent } from './reporteentrenadores/reporteentrenadores.component';
import { ReporteentrenadorComponent } from './reporteentrenador/reporteentrenador.component';
import { ObtenerdatomedicoComponent } from './obtenerdatomedico/obtenerdatomedico.component';
import { ObtenerdatopsicologoComponent } from './obtenerdatopsicologo/obtenerdatopsicologo.component';
import { DatosmedicosnadadorComponent } from './datosmedicosnadador/datosmedicosnadador.component';
import { DatospsicologonadadorComponent } from './datospsicologonadador/datospsicologonadador.component';
import { DatoscompetencianadadorComponent } from './datoscompetencianadador/datoscompetencianadador.component';



export default [
    { path: 'usuario', component: UsuarioComponent},
    { path: 'entrenador', component: EntrenadorComponent },
    { path: 'elasticida', component: ElasticidaComponent },
    { path: 'nutricionales', component: NutricionaleComponent },
    { path: 'antropometrica', component: AntropometricaComponent },
    { path: 'psicologo', component: PsicologoComponent },
    { path: 'medico', component: MedicoComponent },
    { path: 'asistencia', component: AsistenciaComponent },
    { path: 'pago', component: PagoComponent },
    { path: 'representante', component: RepresentanteComponent },
    { path: 'representantenadador', component: RepresentantenadadorComponent },
    { path: 'torneo', component: TorneoComponent },
    { path: 'categoriaDistancia', component: CategoriadistanciaComponent },
    { path: 'tiempoNadador', component: TiemponadadorComponent },
    { path: 'grupo', component: GrupoComponent },
    { path: 'ciudad', component: CiudadComponent },
    { path: 'genero', component: GeneroComponent },
    { path: 'areaNado', component: AreanadoComponent },
    { path: 'categoriaProducto', component: CategoriapruebaComponent },
    { path: 'categoriaTipo', component: CategoriatipoComponent },
    { path: 'tipoNado', component: TiponadoComponent },
    { path: 'tipoPago', component: TipopagoComponent },
    { path: 'pruebaTorneo', component: PruebatorneoComponent },
    { path: 'pruebaNadador', component: PruebanadadorComponent },
    { path: 'planPago', component: PlanPagoComponent },
    { path: 'abonoPago', component: AbonopagoComponent },
    { path: 'graficas', component: GraficasComponent },
    { path: 'graficasUsuario', component: GraficasUsuarioComponent },
    { path: 'asistenciaUsuario', component: AsistenciaUsuarioComponent },
    { path: 'medidaUsuario', component: MedidasUsuarioComponent },
    { path: 'reporte', component: ReportesComponent },
    { path: 'comprobante', component: ComprovanteComponent },
    { path: 'pagoEntrenadores', component: PagoEntrenadoresComponent },
    { path: 'medicos', component: RegistroMedicoComponent },
    { path: 'psicologos', component: RegistroPsicologoComponent },
    { path: 'historiaUsuario', component: HistorialUsuarioComponent },
    { path: 'VerMedidasUsuario', component: VermedidasComponent },
    { path: 'VerAreaMedicaUsuario', component: MedicoUsuarioComponent },
    { path: 'verPago', component: VerpagoComponent },
    { path: 'verTorneo', component: VertorneocompetidaComponent },
    { path: 'verDashboard', component: VerdashboarComponent },
    { path: 'pagarAbono', component: AbonoentrenadorComponent },
    { path: 'Entrenadorgrupo', component: EntrenadorgrupoComponent },
    { path: 'Verentrenadorusuario', component: VerentrenadorusuarioComponent },
    { path: 'reporteentrenadores', component: ReporteentrenadoresComponent },
    { path: 'reporteentrenador', component: ReporteentrenadorComponent },
    { path: 'datosMedico', component: ObtenerdatomedicoComponent },
    { path: 'datosPsicologo', component: ObtenerdatopsicologoComponent },
    { path: 'datoMedicosUsuario', component: DatosmedicosnadadorComponent },
    { path: 'datoPsicologoUsuario', component: DatospsicologonadadorComponent },
    { path: 'datocompetenciaUsuario', component: DatoscompetencianadadorComponent },

    { path: '**', redirectTo: '/notfound' }
] as Routes;
